import { Metadata } from "next";

export async function generateMetadata({
  params,
  searchParams,
}: any): Promise<Metadata> {
  // empty and undefined params
  console.log(params, searchParams);
  // we could make a request to get the product by id

  return {
    title: `next js template app ${params.id}`,
    description: "Generated by create next app",
  };
}

export default function PostsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <header>posts header</header>
      {children}
    </main>
  );
}
